### ISSUE TITLE
Lab O3651-5 needs VS2015 Instructions

### ISSUE THREAD

**Issue by coatsy** [OfficeDev/TrainingContent#117]
Please update Lab for O3651-5 to use the VS2015 dialogs and flow.

**Comment by wictorwilen** [comment]
Basically any lab that uses ASP.NET MVC needs updates for VS2015

**Comment by jthake** [comment]
Good news is that we are working on the updates right now to get this done!

**Comment by wictorwilen** [comment]
Thanks for the update Jeremy!

**Comment by jthake** [comment]
Tasks of this

•         Investigate whether if make VS2015 project type it can be opened in VS2013? 
•         Apparently if you UPGRADE a VS2013 project to vs2015, it will still open in VS2013. What that would mean is that we could just upgrade all visual studio projects to VS2015 and they'd work in both. NET NEW projects would have to be built in VS2013 and UPGRADED for this to work. Confirm this.
•         Visual Studio 2015 screen shot updates and project updates for ALL modules (except O3658 course) e.g. https://github.com/OfficeDev/TrainingContent/issues/117

**Comment by jthake** [comment]
O3653-8 has been updated to VS2015 with #197

**Comment by jthake** [comment]
O3651-3 has been updated to VS2015 with #201

**Comment by jthake** [comment]
O3651-5 has been updated by #204

**Comment by TBag** [comment]
@jthake All modules have been updated to VS 2015 instructions now.  You can close this out.
