### ISSUE TITLE
The ExecuteAsync() method in Preview on Office.js 1.1 is old

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#137]
Where the training modules were updated for Word and Excel to incorporate Office.js 1.1. It used executeAsync(), which actually got refactored to sync(). Essentially this effects these modules:

O3652-4 Deep Dive in Office Excel Add-ins
O3652-2 Deep Dive in Office Word Add-ins
O3651-2 Getting started with Apps for Office

**Comment by TBag** [comment]
I checked and this does not apply to O3651-2 Getting started with Apps for Office.

**Comment by jthake** [comment]
O3651-2 done.

**Comment by jthake** [comment]
@TBag  just to confirm that O3652-2 and O3652-4 have not been done yet. they have updated slide decks you'll want to pull down before you tweak the slide decks. In O3652-9 you can see how this works with .sync and not .executeAsync()

**Comment by jthake** [comment]
#227 done
