### ISSUE TITLE
O3651-1 Overview decks to latest

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#146]
Add Microsoft Graph slide to overview

**Comment by TBag** [comment]
Please send me the slide to add and let me know where you want it added in the deck.

**Comment by jthake** [comment]
Attached is the deck used at Connect();

Slide 35 is most appropriate for overview. but others make sense there too for use and in other module updates.

[Microsoft Graph - Connect - long.pptx](https://github.com/OfficeDev/TrainingContent/files/58896/Microsoft.Graph.-.Connect.-.long.pptx)

**Comment by jthake** [comment]
Fixed in PR #188
