### ISSUE TITLE
O3652-1 add Outlook add-in commands 

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#147]
Add add-in commands to this module for awareness.

**Comment by TBag** [comment]
Please send me the latest slides you would like to use for this.

**Comment by TBag** [comment]
@jthake Please send me the latest slides you would like me to use for the Outlook add-in commands.  Everything else in this module is updated and ready to go.

**Comment by jthake** [comment]
Here you go mate.

[Outlook Add-In Commands.pptx](https://github.com/OfficeDev/TrainingContent/files/73524/Outlook.Add-In.Commands.pptx)
