### ISSUE TITLE
O3651-5 Microsoft Graph Intro Updates

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#150]
This is the level 200 module on APIs

- Slides to explain Microsoft Graph AND direct end points
-- Illustrate direct endpoints in front e.g. Outlook web hooks on direct before graph, time zone on Calendar is another one

Explain Auth options
- Azure AD "app model v1" 
 - Separate auth flow
- Azure AD "app model v2" (Preview)
 - Converged auth

- Point to  Microsoft Graph SDK preview
 - Create a demo sample using new SDK in ASP.NET MVC

**Comment by TBag** [comment]
@jthake Since we are removing SDKs from the training content I did not make a new demo sample using the new SDK in an ASP.NET MVC web app.

**Comment by jthake** [comment]
Fixed in #204
