### ISSUE TITLE
O3653-3 OneDrive API - rewrite from direct endpoints to graph endpoints

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#156]
rewrite from direct endpoints to graph endpoints

**Comment by jthake** [comment]
Here are slides used for OneDrive from connect()
[OneDrive connect slides.pptx](https://github.com/OfficeDev/TrainingContent/files/58630/OneDrive.connect.slides.pptx)

**Comment by jthake** [comment]
@TBag this requires some further instruction from OneDrive PMG Sean Maloney and engineering PM Ryan Gregg

**Comment by TBag** [comment]
@jthake Did you reach out to them already?

**Comment by jthake** [comment]
waiting...

**Comment by jthake** [comment]
NOTE: based on discussion around what is available on v1.0 Microsoft Graph and what is available on the direct endpoint using discovery service. Need to add a section to caveat what isn't available in Graph and how to call direct endpoint. This will be a common scenario where things appear on direct end point first, before appearing in beta Microsoft Graph and then appearing in major release on Microsoft Graph.

**Comment by jthake** [comment]
@TBag is stil working on this module, it has not been updated yet but all bugs will be squashed when it is committed to the repo.

**Comment by TBag** [comment]
Slide added.
