### ISSUE TITLE
O3653-7 OneNote - rewrite from direct endpoints to graph endpoints

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#157]
rewrite from direct endpoints to graph endpoints

**Comment by TBag** [comment]
@jthake - @dianed and I discussed this module today.  Once we complete the code changes and update the deck accordingly I will issue the PR.  I will also email @dianed so she can go through the deck and validate it and make additional content changes in the deck as needed.

**Comment by jthake** [comment]
NOTE: based on discussion around what is available on v1.0 Microsoft Graph and what is available on the direct endpoint using discovery service. Need to add a section to caveat what isn't available in Graph and how to call direct endpoint. This will be a common scenario where things appear on direct end point first, before appearing in beta Microsoft Graph and then appearing in major release on Microsoft Graph.
