### ISSUE TITLE
Update MVA Deep Dive into Office 365 App Model with latest Add-in APIs

### ISSUE THREAD

**Issue by skyms** [OfficeDev/TrainingContent#173]

**Comment by jthake** [comment]
@skyms we have added Office.js 1.1 content to the Word and Excel modules already. This was done in FY16 Q1 by Andrew Connell. What else did you want to add?
Are you specifically asking for add-in commands as these are in Preview right now and out of scope for training content.

**Comment by skyms** [comment]
@jthake Sorry about the confusion. I believe we talked about updating the existing course on Microsoft Virtual Academy with new APIs and stuff as well. Is this the same course we are talking about? https://mva.microsoft.com/en-US/training-courses/deep-dive-into-the-office-365-app-model-8386

Thanks,
sky

**Comment by jthake** [comment]
What exactly did you want added that is generally available now that is not currently included in this training course?

**Comment by skyms** [comment]
The current MVA course is all about old API. I think it would be great to have more new API coverage.

Thanks,
Sky

**Comment by jthake** [comment]
by "old", you mean v1.0 and not v1.1. The video is not up to date but in the slides what you are saying is make it talk about v1.1 by default in all places?
