### ISSUE TITLE
O3653-8 - Deep Dive into the Office 365 Unified API (issues)

### ISSUE THREAD

**Issue by faridskyman** [OfficeDev/TrainingContent#181]
Issue #1: 
Issue Requests to the Unified API's REST Endpoint > 2. Look at the files in your OneDrive for Business...

URL altho updated to https://graph.microsoft.com/v1.0/me/drive/root/children
it does not show me my 10 files i have in my oneDrive.

Issue#2:
Exercise 3: Use the Unified API .NET SDK in an Native Client Application

I configured the completed project and ran, it ask for my credential and then just went to a loading cycle, not loading any directory information...

**Comment by jthake** [comment]
Thank you for reporting this. we are currently in the process of fixing this lab in O3653-8.

**Comment by jthake** [comment]
@TBag just heads up on this for this module.

**Comment by TBag** [comment]
@jthake Got it. Logged.

**Comment by pschaeflein** [comment]
UserOperations.cs, lines 40 & 46. Exceptions are swallowed.

**Comment by jthake** [comment]
Thanks for investigating this @pschaeflein . So the updates that @TBag is making to this module will resolve this for sure.

**Comment by pschaeflein** [comment]
I figured as much. Thanks.


- Paul


________________________________
