### ISSUE TITLE
Bug in Lab 3653-1

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#182]
Issue while doing the lab (O3653-1) and the problem is one can't see 302 code line in fiddler. 

*Issues exist on These steps.
6. Switch to Fiddler. Near the bottom of the session list will be an entry in red with a result code of 502. Before that, there will be a session with a response code of 302.
7. Select "302" entry.

**There is no record for code 302 in fiddler.
on some machines deactivating the Antivirus made the 302 appear - on others that made no difference

**Comment by jthake** [comment]
@Senajs was this replicated on another machine?

**Comment by Senajs** [comment]
@jthake yes it Repros on several machines - see also the mail i sent you with a solution that works - almost all students reported this issue.

**Comment by jthake** [comment]
can you please share this here and not on email for visibility.

**Comment by jthake** [comment]
BTW I have my Fiddler configured to Capture HTTPS CONNECTS and to Decrypt HTTPS traffic while Ignore server certificate errors and all works fine for me.

**Comment by Senajs** [comment]
here is the solution:
Fiddler Setting:
Tools -> Fiddler Options, HTTPS Tab -> Be sure Decrypt HTTPS Traffic is NOT checked

Now navigate to the link below
https://login.microsoftonline.com/[tenant-id]/oauth2/authorize?client_id={client-id}&resource=https://graph.microsoft.com/&redirect_uri=https://dev.office.com&response_type=code

After the page is loaded, do not login yet.
Go back to Fiddler's settings and this time Be sure Decrypt HTTPS Traffic is checked.

Now login and this time you can see the screenshot below (Code value)
 
![fiddler](https://cloud.githubusercontent.com/assets/15032819/11894191/ee4b9b14-a575-11e5-8ca5-fdac023a6b26.png)

Please consider that if you have checked Decrypt HTTPS Traffic before navigating to the link provided above, browser asks for certificate and it can bring some difficulties. The only time I had no issue was the steps described above.

**Comment by TBag** [comment]
The lab no longer references Fiddler. The next PR I do for 3-1 (in just a minute) makes this issue obsolete.

**Comment by Senajs** [comment]
Ok great that was often a cause of problems.
So I will NOT report anything with Fiddler and 3653-1
Regards
Senaj


Von: Todd Baginski [mailto:notifications@github.com]
Gesendet: Montag, 25. Januar 2016 22:22
An: OfficeDev/TrainingContent <TrainingContent@noreply.github.com>
Cc: Senaj Lelic <sl@oneassist.de>
Betreff: Re: [TrainingContent] Bug in Lab 3653-1 (#182)


The lab no longer references Fiddler. The next PR I do for 3-1 (in just a minute) makes this issue obsolete.
