### ISSUE TITLE
Bug in Lab 3653-3

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#183]
Exercise 3 step 7

it should be <IItem>  not  <IITem>

 
"add the following code to read a page of files"
First line Task<IEnumerable<<Item>> instead of IItem

**Comment by jthake** [comment]
@TBag this is a new issue that can be corrected as you fix up O3653-3.

**Comment by TBag** [comment]
@jthake Got it. Logged.

**Comment by jthake** [comment]
@TBag is stil working on this module, it has not been updated yet but all bugs will be squashed when it is committed to the repo.

**Comment by TBag** [comment]
This is now obsolete because the lab is restructured.
