### ISSUE TITLE
O3653-3 bug with VS 2015

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#184]
I am using VS2015 to do lab and experience this error in Exercise 3.

 
![bug](https://cloud.githubusercontent.com/assets/15032819/11738487/5ad2c5d4-9fe3-11e5-9a7a-17d7b81f2089.png)

according to this posting, that caused by bug in Vs2015.

http://stackoverflow.com/questions/31632507/failed-to-acquire-token-silently-call-method-acquiretoken/31951711#31951711

**Comment by tushar-63** [comment]
R u on your organisation LAN. If it is so than try to use your own private connection because the same issue was faced by me and in my case  there was some restrictions in  organisation network.

**Comment by Senajs** [comment]
well we are on MSFTOpen the open Wifi at Microsoft :-)

**Comment by jthake** [comment]
This bug will be resolved when we update the lab to Visual Studio 2015 and use the Microsoft Graph.

**Comment by TBag** [comment]
To resolve this issue you sign out of the app then sign it.  I have seen this issue with many of the labs in the modules.  Signing out and signing in always fixes it.

**Comment by Senajs** [comment]
@TBag so for now sign out and in fixes it and later VS 2015 - right ?

**Comment by TBag** [comment]
@Senajs Yup.  I am about to issue a PR for this module in a minute or two.

**Comment by Senajs** [comment]
@TBag stupid question: whats a PR ? public Relations ?

**Comment by TBag** [comment]
@Senajs Pull Request.  :-)

**Comment by Senajs** [comment]
Ok thy ☺)


Von: Todd Baginski [mailto:notifications@github.com]
Gesendet: Freitag, 29. Januar 2016 18:29
An: OfficeDev/TrainingContent <TrainingContent@noreply.github.com>
Cc: Senaj Lelic <sl@oneassist.de>
Betreff: Re: [TrainingContent] O3653-3 bug with VS 2015 (#184)


@Senajs<https://github.com/Senajs> Pull Request. :-)

**Comment by TBag** [comment]
You're welcome.  Have a good day!

**Comment by Senajs** [comment]
Thanks and Have a nice evening ☺

Von: Todd Baginski [mailto:notifications@github.com]
Gesendet: Freitag, 29. Januar 2016 18:35
An: OfficeDev/TrainingContent <TrainingContent@noreply.github.com>
Cc: Senaj Lelic <sl@oneassist.de>
Betreff: Re: [TrainingContent] O3653-3 bug with VS 2015 (#184)


You're welcome. Have a good day!
