### ISSUE TITLE
O3653-8: CompletedProject - Opening .sln will not open related .csproj

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/TrainingContent#205]
![o3653-8-img-1](https://cloud.githubusercontent.com/assets/8008013/12065995/29c54368-afa6-11e5-8022-e013014a9ec2.jpg)
![o3653-8-img-2](https://cloud.githubusercontent.com/assets/8008013/12065996/2c05f960-afa6-11e5-9bce-8edefdda84c6.jpg)

**Comment by jthake** [comment]
what version of Visaul Studio are you using @pschaeflein . @Tbag just so you know this is an issue with the module you submitted the other day.

**Comment by pschaeflein** [comment]
VS2015, but it doesn’t matter. The .sln includes a folder in the path to the .csproj. (Double-click on the .csproj and everything is fine.)


- Paul

**Comment by jthake** [comment]
OK thanks for reporting this @pschaeflein . HAPPY NEW YEAR!

**Comment by TBag** [comment]
This is fixed and I am committing the changes and issuing a PR now.  Thanks for reporting it @pschaeflein .

**Comment by jthake** [comment]
there is a PR paul had already submitted that i was about ot review and accept
...
