### ISSUE TITLE
Suggestion: Rename confusing variable name - O3653-8: AuthenticationHelper.cs

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/TrainingContent#208]
The AuthenticationHelper class has two constants to refer to the urls used by the solution:

        public const string ResourceBetaUrl = "https://graph.microsoft.com/v1.0/";
        public const string ResourceUrl = "https://graph.microsoft.com/";

The second (ResourceUrl) is used in the token acquisition and refers to the secured resource being requested. The first (ResourceBetaUrl) is the actual endpoint for the api. 

Suggest renaming the first to "EndpointUrl" or something to distinguish it from the token resource. And remove "Beta."

**Comment by jthake** [comment]
@Tbag can you incorporate this in current change?

**Comment by TBag** [comment]
Change done.  As soon as you accept my other PRs I can commit these.

**Comment by jthake** [comment]
Thanks mate!

Thanks @pschaeflein for reporting. #HawkEye

**Comment by pschaeflein** [comment]
Just FYI, this change was not included in the merge referenced above.

**Comment by jthake** [comment]
@TBag  this stil hasn't been changed it seems https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-8%20Deep%20Dive%20into%20the%20Office%20365%20Unified%20API/Lab%20Files/AuthenticationHelper.cs

**Comment by TBag** [comment]
@jthake I just submitted a PR for this fix.
