### ISSUE TITLE
O3653-8: Projects refer to missing file

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/TrainingContent#209]
The certificate file is not in the repo (which is fine). However the project files (LabFiles and CompletedProject) include the file.

![o3653-8-img4](https://cloud.githubusercontent.com/assets/8008013/12067796/d47795e4-afc5-11e5-81d5-a767764dec50.jpg)

**Comment by jthake** [comment]
@tbag can this be addressed please?

**Comment by TBag** [comment]
GitHub stripped this file.  You will need to edit the .gitignore to allow this to be put in the repo.

**Comment by jthake** [comment]
OK i just tweaked the gitignore to allow .pfx, it'll pull it down now. https://github.com/OfficeDev/TrainingContent/commit/1b6150c741a9a78951d6a26b92c7c5337b251fff .

@pschaeflein  do you mind validating?

**Comment by TBag** [comment]
I need to commit the file before he can validate it.  Once my other PRs are accepted I can do that.

**Comment by jthake** [comment]
ah yes, was just checking and i see, it'll ignore it so won't show up in commit. no drama.

**Comment by pschaeflein** [comment]
I ran the project just fine without the file.

**Comment by jthake** [comment]
#211 fixed this.
