### ISSUE TITLE
Lab Starter files for Win 10 UWP lab are Win 8.1 instead of Win 10

### ISSUE THREAD

**Issue by dougperkes** [OfficeDev/TrainingContent#221]
Please update the starter files to be Windows 10 as referenced in the Lab.md file. 

Location: TrainingContent / O3654 / O3654-1 Deep dive into native Universal Windows App Development with Office 365 APIs / Lab / Starter /

**Comment by jthake** [comment]
Thanks for reporting this @dougperkes . I just got @Tbag to put in a pull request #220  that resolves this.
