### ISSUE TITLE
HOLS that reference starter projects don't make sense when hosted on dev.office.com

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#228]
HOLS such as http://dev.office.com/hands-on-labs/1544 that reference starter files like home.css.txt are not clear enough on where to find these files. We have a "see in GitHub" link in top right but people may not see this as they go through the steps. Also when clicked on this goes to the markdown page and not the folder for the module where the starter files are. 
It would be ideal if we had a link in the markdown to the individual file in github directly. e.g. in this case to the raw file https://github.com/OfficeDev/TrainingContent/raw/master/O3652/O3652-4%20Deep%20Dive%20in%20Office%20Excel%20Add-ins/Starter%20Files/Home.css.txt 

We need to go through the HOLS and add these links. The only issue here is if they refer to a folder with a starter project rather than individual file to grab, we may need to just assume they clone the TrainingContent repo down instead. 
We could zip the starter project folder and have it in source control and reference that, but then we have two copies of the same thing. Which becomes hard to maintain unless its automated in the repo.

**Comment by jthake** [comment]
Priority HOLS are:

O3651-1
O3652-3
O3652-4
O3652-1
O3652-2
O3652-7
O3652-6
O3651-2
O3651-3
O3651-5
O3658-1
O3658-6
O3658-4

**Comment by Laskewitz** [comment]
Will try to fix it asap...

**Comment by TBag** [comment]
@jthake Here are the cases we identified on the call today.

1. If a starter file does not contain cod, like an image file or another type of non-code file, just link to the file directly.  There is no need to link to the folder, just link to the file.
2. If a file in the starter files folder has less than 40 lines of code, just include the text from the starter file in the lab.md file and delete the starter file.  This way we do not have to provide a link to the starter file.
3.If a file in the starter files folder has more than 40 lines of code, just link to the starter file from the lab.md file and keep the starter file.  In this scenario, do not show the code in the starter file in the lab.md file.
4. If the lab.md asks a user to use a collection of files in a folder that has a bunch of files in it, like a whole VS solution and VS Projects, then tell the user to clone the GitHub repo and use the files they cloned.

**Comment by jthake** [comment]
Here are the cases we identified on the call today.

1. If a starter file does not contain code, like an image file or another type of non-code file, just link to the RAW file in github directly.  There is no need to link to the github folder in the browser, just link to the file.
2. If a file in the starter files folder has less than 40 lines of code, just include the text from the starter file in the lab.md file and delete the starter file.  This way we do not have to provide a link to the starter file.
3. If a file in the starter files folder has more than 40 lines of code, just link to the RAW starter file in Github from the lab.md file and keep the starter file.  In this scenario, do not show the code in the starter file in the lab.md file.
4. If the lab.md asks a user to use a collection of files in a folder that has a bunch of files in it, like a whole VS solution and VS Projects, then tell the user to clone the GitHub repo and use the files they cloned. The folder should be referred to relative to the root of the repo downloaded locally. The instructions for this are as follows and this should be placed at top of the hands on lab:

> This lab requires you to use multiple starter files from the GitHub location.  You can either download the whole repo as a zip or clone the repo `https://github.com/OfficeDev/TrainingContent.git` for those familiar with git.

**Comment by Laskewitz** [comment]
I think the priority HOLS are fixed now. Will try to fix the rest later this week.
