### ISSUE TITLE
O3651-5 Add-In should be App

### ISSUE THREAD

**Issue by coatsy** [OfficeDev/TrainingContent#238]
Another find and replace issue - O3651-5 pptx slide 6 "Your Add-in" should be "Your App"

**Comment by jthake** [comment]
yes it crept back in. the change i made actually got overwritten by the designer who updated the sldies and pulled the version before.

**Comment by jthake** [comment]
OK I"ve updated that and the one that creeped in again on O3651-1. Thanks @coatsy  ;-)
