### ISSUE TITLE
O3651-5, Bug in Ex 2, Step 2i,

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#241]
There is a utils folder mentioned in the instructions and that the Setttingshelper should be copied there, but the folder is not in the project NOR is it in the instructions to create it
@jthake, @Tbag

**Comment by jthake** [comment]
@TBag you have completed this course and updated, but seems there is still a bug.

**Comment by TBag** [comment]
Just checked the lab.md file in GitHub.  The lab.md already contains the instructions to create the folder and how to copy the file into it.  Perhaps you do not have the latest version of this file?

https://github.com/OfficeDev/TrainingContent/blob/master/O3651/O3651-5%20Getting%20started%20with%20Office%20365%20APIs/Lab.md

**Comment by Senajs** [comment]
@jthake well i pulled Jan 15.. will pull again Feb 15 and test..
