### ISSUE TITLE
O3651-5; Bug in Lab: 2.	Ex 3 1v

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#242]
The Classes ADALTokenCache And ApplicationDbContext are mentioned in the code snippet – but they don’t exist. Only by looking into the “completed projects” folder they can be found and if copied to the exercise folder the problem is fixed.
@jthake, @Tbag

**Comment by jthake** [comment]
@TBag you have completed this course and updated, but seems there is still a bug.

**Comment by TBag** [comment]
ADALTokenCache is mentioned in the code snippet.  ApplicationDbContext is not mentioned in the code snippet.  Please ensure you have the latest version of this module and test again and let me know if something is still causing you issues.  I think you are operating with an old version of this module.

**Comment by Senajs** [comment]
@TBag i pulled the Content on Jan 15 from Github - was the Content updated by then ?
I'll pull it again on feb 15 and submit if i find something..
