### ISSUE TITLE
Bug/remark to lab: OFFICE3653-3

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#247]
additional reports.

after finish exercise5, i feel there is something missing.

exercise5 is about new OneDrive REST API, and code is fully functional, 
but there is no link to the new added OneDrive REST API index view page(https://localhost:44300/OneDriveNewApi)

my opinion is, exercise5 have to describe more about add link to new OneDrive REST API view page.
(ex: edit _Layout.cshtml file found in the Views/Shared folder to add link)

@jthake, @Tbag

**Comment by jthake** [comment]
@TBag is stil working on this module, it has not been updated yet but all bugs will be squashed when it is committed to the repo.

**Comment by TBag** [comment]
This is now obsolete because the lab is restructured.
