### ISSUE TITLE
O3653-3 Completed Project, Exercise 2: Using old version of netfx

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/TrainingContent#278]
I received a compile error on the project in Exercise 2 - not all of the NuGet packages support the old netfx version specified.

https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-3%20Deep%20Dive%20into%20Office%20365%20APIs%20for%20OneDrive%20for%20Business/Completed%20Projects/Exercise02/OneDriveWeb/OneDriveWeb.csproj#L18

(I did not submit a PR since I know TB is pushing changes and I didn't want to conflict.)

**Comment by TBag** [comment]
Hey @pschaeflein,

We have finished our work on this one.  If you already have it fixed and a PR ready to go can you submit it?  You won't interfere with us if you do that.

**Comment by pschaeflein** [comment]
I do, and I will

- Paul

Thumbed from my phone. Please forgive brevity and typos.



On Tue, Feb 23, 2016 at 7:31 AM -0800, "Todd Baginski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @pschaeflein<https://github.com/pschaeflein>,

We have finished our work on this one. If you already have it fixed and a PR ready to go can you submit it? You won't interfere with us if you do that.

-

**Comment by TBag** [comment]
Cool, thanks a bunch!
