### ISSUE TITLE
Bug in Lab of module O3653-8 

### ISSUE THREAD

**Issue by janis-veinbergs** [OfficeDev/TrainingContent#289]
Under Exercise 2, [Issue Requests to the Microsoft Graph REST Endpoint](https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-8%20Deep%20Dive%20into%20the%20Office%20365%20Unified%20API/Lab.md#issue-requests-to-the-microsoft-graph-rest-endpoint), after completing point 4 it is expected to get an Access Denied. But the outcome is that a successful response is returned with group details, because in Exercise 1 under [Grant App Necessary Permissions to the Microsoft Graph](Grant App Necessary Permissions to the Microsoft Graph) we already delegated "Read all groups" permissions.

Should probably try to query /contacts instead of /memberOf, and then we see that if that permission is not delegated, we receive Access is denied message.

@senajs @jthake

**Comment by jthake** [comment]
Adding to workload @TBag
