### ISSUE TITLE
Missing name of the project file to open

### ISSUE THREAD

**Issue by ivarsg** [OfficeDev/TrainingContent#290]
In O3657-2 [Lab, Exercise 1](https://github.com/OfficeDev/TrainingContent/blob/master/O3657/O3657-2%20Creating%20Client%20Side%20Only%20Apps%20with%20Angular%2C%20ADAL%20and%20Office%20365%20APIs/Lab.md#exercise-1-configure-the-starter-project) Point No.2 it is required to "open the project in any text editor...", but no project file name is mentioned. So, it is not clear which file has to be opend.

@senajs @jthake

**Comment by jthake** [comment]
Adding to workload @TBag
