### ISSUE TITLE
O3653-1: Exercise 2: Point 4: Local machine option is missing in configure the debug mode in VS

### ISSUE THREAD

**Issue by ivarsg** [OfficeDev/TrainingContent#292]
In [O3653-1, Exercise 2](https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-1%20Deep%20Dive%20into%20Azure%20AD%20with%20the%20Office%20365%20APIs/Lab.md#exercise-2-add-class-to-implement-authentication-and-represent-the-data-returned-from-the-microsoft-graph) Step 4 it is required to configure the debug mode as shown in picture (which states "Debug / x86 / Local Machine"), but there is no such "Local Machine" option in VS. There are only "Remote Machine", "Device" and "Download New Emulators..." options.

Probably some unstated requirements are not met in my local VS installation (MS Visual Studio Community 2015, v.14.0.24720.00 Update 1) 

@senajs @jthake

**Comment by treneyyro** [comment]
To perform O3653-1, Exercise 2 You need to work on Windows 10 or You need to install Windows 10 emulator. If You want to install an emulator You have to have Visuat Studio 2015 in Professional version.

@senajs

**Comment by jthake** [comment]
What Windows environment are you running on @ivarsg ?

**Comment by ivarsg** [comment]
@jthake I am on Windows 8.1 Pro, x64.
