### ISSUE TITLE
Bug in Lab of module O3653-8 Exercise 3: Compilation fails

### ISSUE THREAD

**Issue by janis-veinbergs** [OfficeDev/TrainingContent#295]
All instances of AuthenticationHelper.ResourceBetaUrl must be replaced with AuthenticationHelper.EndpointUrl for project to compile & work.

@senajs @jthake

**Comment by jthake** [comment]
@TBag adding to your list.

**Comment by chrisbao** [comment]
@janis-veinbergs , we could not reproduce this issue from our end. Could you please let us know how to reproduce this issue and what environment are you using to reproduce this issue?

**Comment by pschaeflein** [comment]
The completed project and lab files are fine. Issue is with the lab steps. PR created.

**Comment by TBag** [comment]
Thanks Paul!
