### ISSUE TITLE
O3652-7 Issues for Exercise 3

### ISSUE THREAD

**Issue by janis-veinbergs** [OfficeDev/TrainingContent#296]
Step 4 should read ClientCredsAddin instead of Office365Contacts 
The point 4.1 seems outdated, as there is no option as "Register Your App". Probably the correct one would be "Azure AD Authentication", which further invalidates the whole 4.1 point.

# Chapter: Setup the ASP.NET MVC Web Application for App-Only Authentication

Point 2: it is not required to set **ida:ClientID** and **ida:AadTenantID**. They were set when Azure AD Connection was added and resulted in duplicate keys being present (with and without ClientID, AadTenantId values). Probably these must be deleted from web.config.

When I reached step 3.1, the AccountController class already existed for me. Could it be that the updated Connections dialog did this for me? It may be that Exercise 3 was written using older VS or older Office tools. I'm using VS 2015 Community Update 1

Code in Step 4.iv and 4.vi.c is the same. I believe code written in 4.iv is invalid and there should be different stuff. The exercise cannot be completed without proper JwtToken class.

Again, in 4.vii code is equal to 4.vi. Code in 4.vii is invalid (or better yet: missing).

I did not proceed to any further chapters.

@senajs @jthake

**Comment by jthake** [comment]
@TBag adding to your list.

**Comment by chrisbao** [comment]
@janis-veinbergs , "Register Your App" is the option in VS 2013 and it seems that you were using VS 2015 to test this module. @jthake , do you think we would upgrade this module to VS 2015?

**Comment by chrisbao** [comment]
Btw do you think would leverage the Graph API to implement the exercises? :)  @jthake

**Comment by jthake** [comment]
We have not updated the SharePoint labs to Visual Studio 2015 like we have the Microsoft Graph modules and Office add-in modules. SharePoint is not on the Microsoft Graph yet, so @chrisbao that would not be possible. It appears we need to update this to Visual STudio 2015 to fix the lab regardless now. @TBag can you please do this?

**Comment by TBag** [comment]
@jthake, We think the reason the lab is broken because @janis-veinbergs tried to run it with VS 2015.  We are waiting on him to confirm.  As far as we know, it works with VS 2013.  Do you still want us to update it to VS 2015?

**Comment by jthake** [comment]
that's a shame that is breaking in VS2015 and not in VS2013. Lets wait for @janis-veinbergs to confirm this first.

**Comment by janis-veinbergs** [comment]
The differences in setting up the connection doesn't prevent to proceed with the lab. However further down the lab there are some code samples, that are invalid. Look at `JwtToken` and the `AppState` models. That's clearly invalid code and meant for other classes (after scrolling down a bit, there is the same code mentioned but for valid purpose).

I didn't proceed onto following chapters as I encountered these classes and understood that would take too much time at DevCamp to create those classes. So i can't validate anything afterwards.

Is that clear what I am trying to say, @jthake, @TBag ?

**Comment by TBag** [comment]
Hi @janis-veinbergs,

We did not create this module so we are trying to get more familiar with it.  Since this lab was designed to be used with Visual Studio 2013 we are testing it with Visual Studio 2013 now to see if it works or not.  Once we figure out if it works with Visual Studio 2013 we will ask @jthake if he wants us to update if for Visual Studio 2015 or not.
