### ISSUE TITLE
Bug in Lab of module O3653-9

### ISSUE THREAD

**Issue by janis-veinbergs** [OfficeDev/TrainingContent#297]
# Exercise 3
Chapter [Issue Requests to the Group API's REST Endpoint via the Microsoft Graph](https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-9%20Groups%20API/Lab.md#issue-requests-to-the-group-apis-rest-endpoint-via-the-microsoft-graph) step 2.2. Endpoint URL from https://graph.microsoft.com/beta/me/joinedGroups should be changed to https://graph.microsoft.com/v1.0/me/memberOf

# Exercise 4
12.ii `string restURL = string.Format("{0}/me/joinedGroups?$select=id,displayName", GraphBetaResourceUrl);` should be changed to `string restURL = string.Format("{0}/me/memberOf?$select=id,displayName", GraphResourceUrl);`

13.ii `string restURL = string.Format("{0}/myorganization/groups?$filter=startswith(displayName,'{1}')", GraphBetaResourceUrl, groupName);` should be changed to `string restURL = string.Format("{0}/{1}/groups?$filter=startswith(displayName,'{2}')", GraphResourceUrl, ConfigurationManager.AppSettings["ida:TenantId"], groupName);`

OR it should be strongly made aware that "myorganization" should be replaced with appropriate value. And stil, `GraphResourceUrl` should be used instead of `GraphBetaResourceUrl`

This should apply everywhere restURL is constructed. On some URLs there is myorganization present, which should be replaced, and for others even "myorganization" is missing. See 14.ii, 15.ii, 16.ii, 17.ii and 18.ii

@senajs @jthake

**Comment by jthake** [comment]
@TBag adding to your list.
