### ISSUE TITLE
O3656-2: REST APIs: Space required in list name, Ceo%20List

### ISSUE THREAD

**Issue by rrkushner** [OfficeDev/TrainingContent#327]
When I click on "Microsoft CEOs" it can't find the list! So I put together a url to verify that the list did exist. But to get it thru the rest api, I had to put a space in the list name:

StringBuilder requestUri = new StringBuilder(_spContext.SPAppWebUrl.ToString())
              .Append("_api/web/lists/getbytitle('Ceo%20List')/items")

**Comment by TBag** [comment]
@rrkushner We found the code you are talking about in O3656-3, not O3656-2.  We are making the assumption that there is a typo in the name for this issue and you meant to say O3656-3.  We will publish the fix shortly after the entire module is tested again and possibly converted to Visual Studio 2015.
