### ISSUE TITLE
Please use shorter paths

### ISSUE THREAD

**Issue by fmuntean** [OfficeDev/TrainingContent#354]
I have the repository mapped to the following folder: D:\GIT\O365TrainingContent
When I try to check out I get the following error:
error: unable to create file O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 1/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java (Filename too long)
Your branch is up-to-date with 'origin/master'.
error: unable to create file O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 2/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java (Filename too long)

Any chance we can shorted / colapse these paths ?

**Comment by TBag** [comment]
Working on it.... :)

**Comment by johnt83** [comment]
Closing this module. It will be addressed by #377.
