### ISSUE TITLE
I think the repo might be a tiny bit to big

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/TrainingContent#36]
Can't even clone it on my highpowered workstation

λ git clone git@github.com:OfficeDev/TrainingContent.git
Cloning into 'TrainingContent'...
remote: Counting objects: 5203, done.
select: Not enough memory4163/5203), 95.80 MiB | 315.00 KiB/s
ffatal: The remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed

**Comment by pbjorklund** [comment]
Yes, this was on my workstation with 16gb ram..

Was just a FYI since things like this usually don't get reported and might
just cause people not move on and not do that PR they were thinking about.


Mvh Patrik Björklund

**Comment by andrewconnell** [comment]
Odd... my machine has 16GB as well.

**Comment by jthake** [comment]
What are you using to do the clone?

**Comment by pbjorklund** [comment]
The Git that comes bundled with cmder

Regards, Patrik Björklund
(sent from mobile)

**Comment by jthake** [comment]
Interesting, I use SmartGit and have pulled it down fine but also in the past have used SourceTree (which is free). Its going to be too hard to start splitting this up into separate repos and discoverability will get worse for us I think.
