### ISSUE TITLE
O3654-5: Shorten file paths

### ISSUE THREAD

**Issue by TBag** [OfficeDev/TrainingContent#380]
The file paths are so long that they exceed the maximum length for a file path. 

Shorten file paths and update all references to file paths in the .MD files and code samples as needed to ensure all instructions and links point to the new file paths.

Here are the new names for the folders:

\O3654-5 iOS
\O3654-5 iOS\01 AAD Prereqs
\O3654-5 iOS\02 ADAL
\O3654-5 iOS\03 O365 OD SDK
\O3654-5 iOS\04 O365 Exc SDK
\O3654-5 iOS\05 O365 SP Lists SDK

Here is the new name for the slide deck:

O3654-5 Native iOS Development in Office 365 with the Microsoft Graph API.pptx

**Comment by pschaeflein** [comment]
Using the following command will update the local config and fetch all files:
`git clone -c core.longpaths=true https://github.com/OfficeDev/TrainingContent.git`
