### ISSUE TITLE
/Teams/03 Bots Module: Sideload guide not updated after release

### ISSUE THREAD

**Issue by panjkov** [OfficeDev/TrainingContent#399]
[Applies to Teams labs https://github.com/OfficeDev/TrainingContent/tree/master/Teams ]
Hi,
after Teams release, existing sideloading guide for bots and tabs is no longer valid and should be updated to new version.
New sideloading guidance for tabs and bots is available on https://msdn.microsoft.com/en-us/microsoft-teams/sideload

**Comment by TBag** [comment]
Update lab.md in Bot Teams Module to follow the steps in the article linked above.
