### ISSUE TITLE
Please add an example of an App accessing Exchange using App-Only Flow

### ISSUE THREAD

**Issue by arunv-msft** [OfficeDev/TrainingContent#448]
Client credentials flow is an important use-case that we want to market towards. Even one similar to email(https://github.com/OfficeDev/TrainingContent/blob/master/Exchange/01%20Deep%20Dive%20into%20Office%20365%20with%20the%20Microsoft%20Graph%20API%20for%20Calendar%2C%20Mail%2C%20and%20Contacts/Lab.md) would be a good start

**Comment by VesaJuvonen** [comment]
We closed this issue as it had not activity within last 210 days. This generic process we have decided to perform for issues, which have not been explicitly marked still to be work in progress based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
