### ISSUE TITLE
Teams: Lab1

### ISSUE THREAD

**Issue by MaxMelcher** [OfficeDev/TrainingContent#462]
The lab 1 is unfortunately broken: 
- The manifest schema file has changed
- - the icons are handled different
- - the login.microsoftonline.com must be included otherwise nothing happens during a login
- - the configuration page is set differently
- the graph endpoint has changed 
- - the sharepoint column values are now in .fields and not .columnset
- the authentication window does not close

I am working on a PR to fix that.

**Comment by pschaeflein** [comment]
FYI, Teams modules 4 and 5 are the most current.
