### ISSUE TITLE
Incorrect code snippets for teams1app1tabtab.ts and auth.ts

### ISSUE THREAD

**Issue by forktrucka** [OfficeDev/TrainingContent#464]
on this page

https://github.com/OfficeDev/TrainingContent/blob/master/Teams/04%20Fundamentals%20of%20Microsoft%20Teams/Lab.md#exercise2

public doStuff() {
  let button = document.getElementById('getDataButton');
  button!.addEventListener('click', e => { this.refresh(); });

  microsoftTeams.getContext((context: microsoftTeams.Context) => {
    TeamsTheme.fix(context);
    this.groupId = context.groupId;
    // hack
    if (context.entityId) {
      this.configuration = context.entityId;
    }
  });

  let element = document.getElementById('app');
  if (element) {
    element.innerHTML = `The value is: ${this.configuration}`;
  }
});

SHouldn't have the");" on the end

code snippet for auth.ts is missing the curly bracket on the end, and does not compile when running msal.

ts-loader: Using typescript@2.4.2 and X:\teams-app1\teams-app-1\tsconfig-client.json
[15:49:38] [Webpack error] (undefined) X:\teams-app1\teams-app-1\src\app\scripts\auth.ts
(26,13): error TS2554: Expected 1 arguments, but got 3.
[15:49:38] [Webpack error] (undefined) ./src/app/scripts/auth.ts
(26,13): error TS2554: Expected 1 arguments, but got 3.

I suspect maybe that the MSAL library has changed since the instructions were created. I am using MSAL msal@0.1.2

![image](https://user-images.githubusercontent.com/17393932/31803209-f8cfdfbe-b5ae-11e7-9be0-f392e9976532.png)

**Comment by pschaeflein** [comment]
Thanks for the bug report.  Yes, MSAL was updated. The submitted fix is to explicitly declare the version of MSAL that the code requires (0.1.1).

**Comment by VesaJuvonen** [comment]
Closing as fix has been merged with #467.
