### ISSUE TITLE
E:/_teams/teams-app1/node_modules/msal/out/msal.d.ts not found

### ISSUE THREAD

**Issue by medhatelmasry** [OfficeDev/TrainingContent#472]
I am organizing an O365 bootcamp in 10 days time in Vancouver, Canada. One of the topics that will be covered is Teams. I am going through the third and last lab in the "Fundamentals of Microsoft Teams". Code in the **adminconsent.ts** contains this:

reference path="../../../node_modules/msal/out/msal.d.ts"

Even though I ran the "npm install msal" command successfully, I am experiencing this error when running the "gulp build" command:

TS6053: File 'E:/_teams/teams-app1/node_modules/msal/out/msal.d.ts' not found.

I searched for msal.d.ts under the node_modules/msal directory and could not find it. Am I missing something?

Thanks,
Medhat

**Comment by pschaeflein** [comment]
Thanks for alerting me about this issue. The MSAL library was restructured after the lab was written, and you found a place where an edit is required.:)

The easiest work-around is to install the older version of the MSAL library:
`npm install msal@0.1.1`

For existing projects, uninstall the package first.

**Comment by medhatelmasry** [comment]
That worked. It gave me so errors when I ran the "npm install msal@0.1.1
--save" command in a Powershell window running as admin. It completed fine
when I ran it in a cmd window as admin.

Thanks for your help.


Regards,
Medhat Elmasry

**Comment by VesaJuvonen** [comment]
Closing as seems to be solved.
