### ISSUE TITLE
Ripple fire event not a function

### ISSUE THREAD

**Issue by hubflyMobile** [OfficeDev/TrainingContent#477]
Hi, 

   I've  to use   O365 login in cordova .. in this stage I've found one issue ... the issue is **Uncaught TypeError: window.opener.__rippleFireEvent is not a function**  ... Kindly help me .....

I've  one more question ...O365 plugin install in cordova mobile app... kindly help me...it is opening up in a new browser window. is this correct or do you have any better alternative..

**Comment by VesaJuvonen** [comment]
Unfortunately, we can't help with this question from this issue list. This issue list is for reporting issues in the Office 365 training materials and to ensure that those are fixed. As your question seem to be quite generic, this is not, unfortunately, the right location for that.
