### ISSUE TITLE
Web Addin Problem

### ISSUE THREAD

**Issue by FullHouse2222** [OfficeDev/TrainingContent#533]
There is no custom Show Taskpane button in the Home tab. Can you help me analyze what causes? Thank you

**Comment by andrewconnell** [comment]
Please review the lab steps as we've verified they are working... you can also compare your project to the included project to see where the difference is. 

If you have a specific question, please feel free to submit another issue, but this list isn't monitored / setup for open Q/A or debugging.

**Comment by andrewconnell** [comment]
#please-close
