### ISSUE TITLE
Can't find bot builder v3

### ISSUE THREAD

**Issue by metro-mark** [OfficeDev/TrainingContent#534]
I have checked visual studio and looked at lab.md file under teams bots lab and it seems that all that is available is v4. Could someone look into this and update the lab so that it either works with v4 or let the world know how to still download v3 and continue with the lab?

**Comment by pschaeflein** [comment]
This lab builds upon the Azure Bot service. I've opened an issue on the Bots documentation page to track the missing template: https://github.com/MicrosoftDocs/bot-docs/issues/370
