### ISSUE TITLE
ConnectorClient var name in Bot Lab in Lab Files/HandleSystemMessageAsync.cs

### ISSUE THREAD

**Issue by ajglasser** [OfficeDev/TrainingContent#539]
The project file of Controllers/MessagesController.cs has a method HandleSystemMessageAsync. This method code is in the lab.md and also in the Lab Files/HandleSystemMessageAsync.cs to be pasted in the class.

Shouldn't the ConnectorClient object saved as
var **connector** = new ConnectorClient(new Uri(message.ServiceUrl));
be renamed to "client"
var **client**= new ConnectorClient(new Uri(message.ServiceUrl));

this way all of the references to "client" in the class would be correct? Otherwise it wouldn't build.

**Comment by pschaeflein** [comment]
Thanks for the feedback!

Unfortunately, I don’t quite follow where the rename should happen. You could submit a PR, or reply with the file path/name and line number. That would help tremendously. ;)

**Comment by ajglasser** [comment]
No problem, thanks for reviewing. 
in the Controllers/MessagesController.cs file in the HandleSystemMessageAsync method,
the var for ConnectorClient should either change to **client** or all of the references to client in the method should change to the var name **connector** as you see here in the last two lines.

`
private async Task<Activity> HandleSystemMessageAsync(Activity message)

		{
			TeamEventBase eventData = message.GetConversationUpdateData();
			switch (eventData.EventType)
			{
				case TeamEventType.MembersAdded:
					var connector = new ConnectorClient(new Uri(message.ServiceUrl));
                                        client.SetRetryPolicy(
`

It's a simple fix, but what the confusion for me was that in the **Lab readme** it has this reference as two different names **connector & client**. Also the file in TrainingContent-master\Teams\01 Bots, Messaging Extensions and Cards\Lab Files\HandleSystemMessageAsync.cs has the same mix match.

The solution code in TrainingContent-master\Teams\01 Bots, Messaging Extensions and Cards\Demos is correct though, all references to the variable is **connector**.
I was thinking that the Lab readme and the TrainingContent-master\Teams\01 Bots, Messaging Extensions and Cards\Lab Files\HandleSystemMessageAsync.cs could be updated to match the Demo solution. 
It wasn't really a big deal, it was easy to correct on my own. Just wanted to share!

**Comment by BobGerman** [comment]
I'm working on a PR for this and a number of other issues where by following the instructions the code fails to compile or there are runtime errors. I've still got some labs to get through but if you'd like to follow along while I'm working here is the fork and branch: https://github.com/BobGerman/TrainingContent/tree/bobg

I will do a PR hopefully in the next day or so with all the fixes I've found.

**Comment by ajglasser** [comment]
Yes, I've kept a list of about 12~ code issues, missing files, and readme incomplete instructions. I've been able to get everything working and have the code. I'll look at the branch you have and contribute as soon as I can.

**Comment by BobGerman** [comment]
OK maybe we can cross-check our work to ensure future users don't run into these issues?
Thanks!

**Comment by BobGerman** [comment]
Should be fixed in the PR just merged ... thanks!
