### ISSUE TITLE
Universal app lab compilation error for windows phone

### ISSUE THREAD

**Issue by sowmyancs** [OfficeDev/TrainingContent#54]
Hello Team,

First of all thank you so much for excellent number of resources and your tremendous work on developing these samples. Its very helpful.

While testing the lab for the Universal app with office 365 API (O3654-1 Deep dive into native Universal Windows App Development with Office 365 APIs) , got an issue with the compilation of windows phone project.

2>E:\My Presentations\TR20\Universal apps\Starter\HubApp2\HubApp2.Shared\O365Helpers\EventViewModel.cs(29,9,29,27): error CS0246: The type or namespace name 'CalendarOperations' could not be found (are you missing a using directive or an assembly reference?)

When I looked at the CalendarOperations class it is marked only for windows app not for windows phone. 

So want to clarify is this sample is only for windows store app and implementation of windows phone is not yet done right ?

Thanks,
Sowmyan

**Comment by jthake** [comment]
Apologies for missing this. Can you confirm that you are using the most up to date Office 365 Tools in Visual Studio?

**Comment by jthake** [comment]
@sowmyancs ?

**Comment by jthake** [comment]
No response
