### ISSUE TITLE
list-services should be updated to sharepoint-services

### ISSUE THREAD

**Issue by darwaishx** [OfficeDev/TrainingContent#55]
compile 'com.microsoft.services:list-services:0.11.1' should be updated to sharepoint-services

**Comment by jthake** [comment]
Thanks for the feedback, what module are you referring to?

**Comment by jthake** [comment]
@darwaishx  any idea what module you are refering to?

**Comment by andrewconnell** [comment]
Hey @jthake that looks like O3654-4... Android.

**Comment by jthake** [comment]
this was updated on Slide 17.

**Comment by jthake** [comment]
updated in #155
