### ISSUE TITLE
Testing using BotBuilder v4 SDK

### ISSUE THREAD

**Issue by ac2707** [OfficeDev/TrainingContent#587]
On Lab 1 - 01 Bots, Messaging Extensions and Cards 
testing using bot builder v4, echoBot template in VS 2017 :
-web.config is no longer part of the project., added the settings to .bot file instead.
-Updated manifest.json as specified in the manual, but the zip file is not created in the build output folder bin on building the solution.
- Controllers/MessagesController.cs is to be updated as per the manual, which is no longer part of the project in the new template 
Not sure how to proceed on this lab with Bot builder v4 templates, please advise.

Thanks.

**Comment by pschaeflein** [comment]
The Teams modules in this repo do not use BotBuilder v4.

**Comment by andrewconnell** [comment]
@pschaeflein is correct... #please-close
