### ISSUE TITLE
Incomplete code for the Authentication Lab 

### ISSUE THREAD

**Issue by ac2707** [OfficeDev/TrainingContent#588]
Exercise 1 :
Followed the settings mentioned in the exercise for azure portal - error below -
![image](https://user-images.githubusercontent.com/49182510/56883178-8835d480-6a83-11e9-846a-e959aa6fbc79.png)

Exercise 2: Issues with the code added to MessagesController.cs and CommandHandlers.cs, Errors on building the solution -

![image](https://user-images.githubusercontent.com/49182510/56880854-fb3b4d00-6a7b-11e9-8f4e-c9a20ee65b6d.png)
Can you please provide the missing code here .. Thanks

**Comment by pschaeflein** [comment]
The IsTeamsVerificationInvoke method is part of the Microsoft.Bot.Connector package.

https://www.nuget.org/packages/Microsoft.Bot.Connector/3.15.2.2

**Comment by ac2707** [comment]
Lab 3 - Exercise 2 - all settings & code as per manual.
Below warnings:
![image](https://user-images.githubusercontent.com/49182510/57014396-83ad1f80-6c2d-11e9-9c4c-b440c4e48c3a.png)
Bot channel created in Azure doesn't respond to messages.
Is it because of the warnings - async calls being treated as sync calls ? Please advise
