### ISSUE TITLE
Use vue file instead typescript

### ISSUE THREAD

**Issue by jvaca92** [OfficeDev/TrainingContent#601]
I would have question about example project where you have used vue with typescript if can be used clear vue files instead of typescript and which changes would be required for webpack config.

Thank you

**Comment by andrewconnell** [comment]
This isn't the right forum for this. There are plenty of examples & tutorials on the internet showing how to create a Vue project with pure JavaScript. You can create the project with JavaScript, but the sample in this repo uses TypeScript.

**Comment by andrewconnell** [comment]
#please-close
