### ISSUE TITLE
Not receiving the token response from MSAL

### ISSUE THREAD

**Issue by NischaiV** [OfficeDev/TrainingContent#606]
I have a custom app loaded in MS Teams and it simulates the authentication process using MSAL. I use acquireTokenSilent(..) and acquireTokenPopup(..) methods in different use cases. But in both cases, I am not receiving the tokenResponse after the methods are called. Due to this, the authentication is broken. I noticed that this happens only when I try from within Teams app/an iFrame. In normal cases, it works fine. I have dowdloaded the sample code from Azure apllication page > quick start and am using the same.

I also saw few issues already raised on this topic, eg: [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/222) issue is closed mentioning that iFrame use case is not supported by MSAL.

But in contrary to that, [this video](https://www.youtube.com/watch?v=xLjT1Hw5a1E&t=39s) at 24:34 talks about support of Identity platform fro MS Teams.

Could you kindly clarify if MSAL can be used for authentication within MS Teams?

**Comment by NischaiV** [comment]
> This lab uses MSAL in a tab: [Exercise 3: Call the Microsoft Graph API inside a tab](https://github.com/OfficeDev/TrainingContent/blob/master/Teams/04%20Fundamentals%20of%20Microsoft%20Teams/Lab.md#exercise3)

Yes @pschaeflein, I went through it already. I am using similar code(not in ts, but in js). But I still do not receive the tokenResponse after calling the acquireTokenSilent(..)/acquireTokenPopup(..) methods.

**Comment by andrewconnell** [comment]
This module was retired in favor of new modules that use the latest SDKs. All Teams modules have been validated as for the last 4 weeks... #please-close
