### ISSUE TITLE
Query: Support without ngrok?

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/TrainingContent#610]
Hi,
Thanks for nice write up on Bot (https://github.com/OfficeDev/TrainingContent/blob/master/Teams/01%20Bots%2C%20Messaging%20Extensions%20and%20Cards/Lab.md)

In Production environment, how ngrok should be replaced?

**Comment by pschaeflein** [comment]
Deploy the bot to a location that is accessible from the internet.

**Comment by nanddeepn** [comment]
Hi @pschaeflein 
Thank you for reply.
While we register Bot with Azure, the messaging end point is: https://[from-ngrok].ngrok.io/api/Messages

Please suggest, what location can be specified here in a Production environment?
Thanks!

**Comment by AnupamRanku** [comment]
Hi @nanddeepn 
ngrok is used during the development phase. It allows us to build and test the bot without publishing  the app on Azure (or other hosting environments). Once you decide to publish your app, you can follow the steps below (or any other web app deployment steps).
https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-nodejs-in-azure

Your bot endpoint will become:  https://<yoursite>/api/messages

**Comment by andrewconnell** [comment]
answered... #please-close
