### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by DeanGross** [OfficeDev/TrainingContent#627]
The links to the demos on TrainingContent/Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/ are all broken

**Comment by andrewconnell** [comment]
Thanks... will get this fixed. They are all pointing to the demo subfolders in that same folder. You can still get to them by navigating through the folders.

**Comment by andrewconnell** [comment]
#please-close
