### ISSUE TITLE
Error 404: Cannot find webpage  Teams Lab Files\cardtemplate.json 

### ISSUE THREAD

**Issue by kusiroll** [OfficeDev/TrainingContent#665]
The link to this file cannot be found any help with this. https://github.com/OfficeDev/TrainingContent/blob/master/Teams/01%20Bots%2C%20Messaging%20Extensions%20and%20Cards/Lab%20Files%5Ccardtemplate.json

**Comment by kusiroll** [comment]
ok i think this might be an error in the Lab.md file as another similar link on the repo works
https://github.com/OfficeDev/TrainingContent/blob/master/Teams/01%20Bots%2C%20Messaging%20Extensions%20and%20Cards/Lab%20Files/cardtemplate.json

**Comment by andrewconnell** [comment]
This module was retired and has been replaced by new modules. We've validated all Teams modules are current and working as of hte last few weeks. Thanks! #please-close
