### ISSUE TITLE
Error in LearnPersonalTab.tsx

### ISSUE THREAD

**Issue by CloudHotShot** [OfficeDev/TrainingContent#666]
Performing exercise on page https://docs.microsoft.com/en-us/learn/modules/embedded-web-experiences/3-exercise-create-custom-teams-personal-tab

For file ./src/app/scripts/learnPersonalTab/LearnPersonalTab.tsx, everywhere this line exists -> this.setState(Object.assign({}, this.state
I get this error: [TS2339] Property 'assign' does not exist on type 'ObjectConstructor'.

I copied your source and still same error.

**Comment by andrewconnell** [comment]
This was addressed in the latest refresh. Since the lab was published, Microsoft deprecated and pulled the Stardust library breaking anything that used it, including this lab. We've updated the module to use the FluentUI library instead.

#please-close
