### ISSUE TITLE
Dialog boxes do not match up with my client

### ISSUE THREAD

**Issue by johnseto** [OfficeDev/TrainingContent#75]
I have VS2013 Update 4 installed but none of the dialog boxes in the training material match up with my dialog boxes. 

Is this right?

**Comment by jthake** [comment]
Yes they may have changed slightly. Which ones are you referring to? can you give links to the slide decks or pages? I'll get them updated.

**Comment by johnseto** [comment]
Hi Jeremy,

It this lab  > https://github.com/OfficeDev/TrainingContent/blob/05a75743f889ca2185c46a7253390053ce0f24a2/O3653/O3653-4%20Deep%20Dive%20into%20Office%20365%20APIs%20for%20SharePoint%20Site%20services/Lab.md

O3653-4 Deep Dive into Office 365 APIs for SharePoint Site services

Cheers
John

**Comment by chakkaradeep** [comment]
@johnseto Can you please be more specific in which dialog boxes are different? It would help us understand the issue here.

**Comment by johnseto** [comment]
yes I will go through every dialog box and get back to you

**Comment by johnseto** [comment]
Are you ok for me to update to Update 4 dialogs?

**Comment by jthake** [comment]
If you would like to that would be great to submit a pull request.

**Comment by andrewconnell** [comment]
Hey @johnseto make sure you have the latest updates to the repo because I updated this lab recently and I fixed some of these.

**Comment by jthake** [comment]
no response
