### ISSUE TITLE
Cannot Add a Connected Service

### ISSUE THREAD

**Issue by JorgeRi** [OfficeDev/TrainingContent#83]
Hi,
I get the an error when I try to add a Connected Service:
The specified credentials don't have sufficient privileges to make this request.

Which are the permissions needed for this? I'm able to create an Azure Active Directory with my account.

Also, is there not any other way to add the dll's directly to the project? As I cannot add the office365.exhange.portable.dll

**Comment by jthake** [comment]
So sorry for not getting back to you on this @JorgeRi . Did you overcome this?

**Comment by andrewconnell** [comment]
@JorgeRi You can get the DLL's by simply adding the NuGet packages to your project. The one you're looking for is https://www.nuget.org/packages/microsoft.office365.outlookservices.

However as for running the Connected Service wizard... is the error coming from Visual Studio when you try to run it, or is the error coming form Azure? Make sure you login using the correct Azure AD account. that has access to manage AzureAD items when the dialog comes up. if the error is coming from VS, have you tried running VS as an administrator?

**Comment by jthake** [comment]
No response
