### ISSUE TITLE
NullExceptionError on ClientSecret

### ISSUE THREAD

**Issue by jasonsargood** [OfficeDev/TrainingContent#91]
When following the LAB example I found a problem in that the settingsHelper class 

public static string ClientSecret {
      get { return ConfigurationManager.AppSettings["ida:Passwordt"]; }
    }

However the web config uses the following to store the clientsecret

<add key="ida:ClientSecret" value="**********************************************" />

After changing the settingsHelper class to match my app settings in web config everything worked as expected

**Comment by dougperkes** [comment]
Probably the better alternative for this lab is to remove step 14 which sets the AppPrincipal to Internal:

		Replace the contents with ``<Internal/>`` so it looks like the following markup:

		<AppPrincipal>
		  <Internal/>
		</AppPrincipal>

The lab completes well without this change.

**Comment by jthake** [comment]
What hands on lab are you referring to @dougperkes ?

**Comment by dougperkes** [comment]
Sorry, I should have included that. Here's the file:
TrainingContent/O3651/O3651-3 Getting started with Apps for SharePoint/Lab.md

Next time I'll give you a pull request instead :-)

**Comment by TBag** [comment]
Tested on 2 different machines without issue.  You can close this one out, Jeremy.

**Comment by jthake** [comment]
I'm waiting on @dougperkes to confirm whether he still gets the issue with the hands on lab as it stands without any changes. I get you've checked it on 2 diff machines @TBag , can you list what OS, VS and tools version you are using?

**Comment by TBag** [comment]
@jthake I'll get that info and let you know.

**Comment by TBag** [comment]
We tested on the following machines:

* Windows 10 Pro, VS2 013 w/ Update 5
* Windows Server 2012 R2, VS 2013 w/ Update 5

**Comment by dougperkes** [comment]
I tested with VS 2015. Everything seems to be working correctly. Thanks!

**Comment by jthake** [comment]
Thanks for update @dougperkes
