### ISSUE TITLE
AntiForgery error

### ISSUE THREAD

**Issue by jasonsargood** [OfficeDev/TrainingContent#92]
I get the following after signing in and then clicking on the Create New Contact link

I can sign in OK and launch the webpage and it's shows that I am signed in with the right user however when I try to create a contact I get the following error

{"A claim of type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier' or 'http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider' was not present on the provided ClaimsIdentity. To enable anti-forgery token support with claims-based authentication, please verify that the configured claims provider is providing both of these claims on the ClaimsIdentity instances it generates. If the configured claims provider instead uses a different claim type as a unique identifier, it can be configured by setting the static property AntiForgeryConfig.UniqueClaimTypeIdentifier."}

**Comment by jasonsargood** [comment]
Resolved by adding the following to GLOBAL.ASAX

AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.NameIdentifier;

**Comment by jthake** [comment]
@jasonsargood  what training module was this relevant too? want to make sure our content is accurate.

**Comment by jasonsargood** [comment]
Sorry it was OS3653

**Comment by andrewconnell** [comment]
@jasonsargood - What module? you listed the course (course #3... O3653) but it would help if you could narrow it down to a course or a project within a course to investigate. Even a link to the ASAX file would be helpful.

**Comment by andrewconnell** [comment]
I think this was addressed when we split the O3653-2 module that covered all three Exchange data types (mail, contacts & calendar) into different modules in [PR#100](https://github.com/OfficeDev/TrainingContent/pull/100). The new module O3653-14 includes this in the `global.asax.cs` file.

Ref:
https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-14%20Deep%20Dive%20into%20Office%20365%20APIs%20for%20Contacts/Completed%20Solutions/Global.asax.cs
